-- Ads active count history for Direct Response Vault.
-- Run this once in the Supabase SQL editor before deploying the scraper update.

alter table public.ofertas
add column if not exists anuncios_ativos_atualizado_em timestamptz;

alter table public.ofertas
add column if not exists nome text,
add column if not exists niche text,
add column if not exists tipo text,
add column if not exists lingua text,
add column if not exists capa text,
add column if not exists link_biblioteca text,
add column if not exists links_biblioteca_adicionais text,
add column if not exists link_oferta text,
add column if not exists link_checkout text,
add column if not exists plataforma_checkout text,
add column if not exists link_presell text,
add column if not exists links_criativos jsonb,
add column if not exists link_drive text;

update public.ofertas
set
    nome = coalesce(nome, oferta_data ->> 'nome'),
    niche = coalesce(niche, oferta_data ->> 'niche'),
    tipo = coalesce(tipo, oferta_data ->> 'tipo'),
    lingua = coalesce(lingua, oferta_data ->> 'lingua'),
    capa = coalesce(capa, oferta_data ->> 'capa'),
    link_biblioteca = coalesce(link_biblioteca, oferta_data ->> 'linkBiblioteca'),
    links_biblioteca_adicionais = coalesce(links_biblioteca_adicionais, oferta_data ->> 'linksBibliotecaAdicionais'),
    link_oferta = coalesce(link_oferta, oferta_data ->> 'linkOferta', oferta_data ->> 'linkCloaker'),
    link_checkout = coalesce(link_checkout, oferta_data ->> 'linkCheckout'),
    plataforma_checkout = coalesce(plataforma_checkout, oferta_data ->> 'plataformaCheckout'),
    link_presell = coalesce(link_presell, oferta_data ->> 'linkPresell', oferta_data ->> 'linkPaginas'),
    links_criativos = coalesce(links_criativos, oferta_data -> 'linksCriativos', oferta_data -> 'linkCreatives'),
    link_drive = coalesce(link_drive, oferta_data ->> 'linkDrive')
where oferta_data is not null;

create index if not exists idx_ofertas_dashboard_order
on public.ofertas (id desc);

create index if not exists idx_ofertas_filters
on public.ofertas (niche, lingua, tipo, plataforma_checkout);

create table if not exists public.oferta_ads_leituras (
    id bigint generated by default as identity primary key,
    oferta_id bigint not null references public.ofertas(id) on delete cascade,
    anuncios_ativos integer,
    lido_em timestamptz not null default now(),
    fonte text not null default 'github_actions',
    link_biblioteca text,
    status text not null default 'success',
    erro text,
    created_at timestamptz not null default now(),
    constraint oferta_ads_leituras_ads_non_negative
        check (anuncios_ativos is null or anuncios_ativos >= 0),
    constraint oferta_ads_leituras_status_check
        check (status in ('success', 'failed')),
    constraint oferta_ads_leituras_unique_source_read
        unique (oferta_id, lido_em, fonte)
);

create index if not exists idx_oferta_ads_leituras_oferta_lido_em
on public.oferta_ads_leituras (oferta_id, lido_em desc);

create index if not exists idx_oferta_ads_leituras_recent_success
on public.oferta_ads_leituras (lido_em desc)
where status = 'success';

alter table public.oferta_ads_leituras enable row level security;

drop policy if exists "Authenticated users can read ads history" on public.oferta_ads_leituras;
create policy "Authenticated users can read ads history"
on public.oferta_ads_leituras
for select
to authenticated
using (true);

insert into public.oferta_ads_leituras (
    oferta_id,
    anuncios_ativos,
    lido_em,
    fonte,
    status
)
select
    id,
    anuncios_ativos,
    coalesce(anuncios_ativos_atualizado_em, created_at, now()),
    'backfill',
    'success'
from public.ofertas
where anuncios_ativos is not null
on conflict (oferta_id, lido_em, fonte) do nothing;

delete from public.oferta_ads_leituras
where lido_em < now() - interval '7 days';
