-- Ads active count history for Direct Response Vault.
-- Run this once in the Supabase SQL editor before deploying the scraper update.

alter table public.ofertas
add column if not exists anuncios_ativos_atualizado_em timestamptz;

alter table public.ofertas
add column if not exists ads_monitoring_status text not null default 'active',
add column if not exists ads_zero_since timestamptz,
add column if not exists ads_last_positive_at timestamptz,
add column if not exists ads_inactivated_at timestamptz,
add column if not exists ads_next_check_at timestamptz;

alter table public.ofertas
alter column ads_monitoring_status set default 'active';

update public.ofertas
set ads_monitoring_status = 'active'
where ads_monitoring_status is null;

alter table public.ofertas
alter column ads_monitoring_status set not null;

alter table public.ofertas
add column if not exists nome text,
add column if not exists niche text,
add column if not exists tipo text,
add column if not exists lingua text,
add column if not exists capa text,
add column if not exists link_biblioteca text,
add column if not exists links_biblioteca_adicionais text,
add column if not exists link_oferta text,
add column if not exists link_checkout text,
add column if not exists plataforma_checkout text,
add column if not exists link_presell text,
add column if not exists links_criativos jsonb,
add column if not exists link_drive text;

update public.ofertas
set
    nome = coalesce(nome, oferta_data ->> 'nome'),
    niche = coalesce(niche, oferta_data ->> 'niche'),
    tipo = coalesce(tipo, oferta_data ->> 'tipo'),
    lingua = coalesce(lingua, oferta_data ->> 'lingua'),
    capa = coalesce(capa, oferta_data ->> 'capa'),
    link_biblioteca = coalesce(link_biblioteca, oferta_data ->> 'linkBiblioteca'),
    links_biblioteca_adicionais = coalesce(links_biblioteca_adicionais, oferta_data ->> 'linksBibliotecaAdicionais'),
    link_oferta = coalesce(link_oferta, oferta_data ->> 'linkOferta', oferta_data ->> 'linkCloaker'),
    link_checkout = coalesce(link_checkout, oferta_data ->> 'linkCheckout'),
    plataforma_checkout = coalesce(plataforma_checkout, oferta_data ->> 'plataformaCheckout'),
    link_presell = coalesce(link_presell, oferta_data ->> 'linkPresell', oferta_data ->> 'linkPaginas'),
    links_criativos = coalesce(links_criativos, oferta_data -> 'linksCriativos', oferta_data -> 'linkCreatives'),
    link_drive = coalesce(link_drive, oferta_data ->> 'linkDrive')
where oferta_data is not null;

create index if not exists idx_ofertas_dashboard_order
on public.ofertas (id desc);

create index if not exists idx_ofertas_filters
on public.ofertas (niche, lingua, tipo, plataforma_checkout);

alter table public.ofertas
drop constraint if exists ofertas_ads_monitoring_status_check;

alter table public.ofertas
add constraint ofertas_ads_monitoring_status_check
check (ads_monitoring_status in ('active', 'cooldown', 'inactive'));

create index if not exists idx_ofertas_ads_monitoring_status
on public.ofertas (ads_monitoring_status, ads_next_check_at);

create table if not exists public.oferta_ads_leituras (
    id bigint generated by default as identity primary key,
    oferta_id bigint not null references public.ofertas(id) on delete cascade,
    anuncios_ativos integer,
    lido_em timestamptz not null default now(),
    fonte text not null default 'github_actions',
    link_biblioteca text,
    status text not null default 'success',
    erro text,
    created_at timestamptz not null default now(),
    constraint oferta_ads_leituras_ads_non_negative
        check (anuncios_ativos is null or anuncios_ativos >= 0),
    constraint oferta_ads_leituras_status_check
        check (status in ('success', 'failed')),
    constraint oferta_ads_leituras_unique_source_read
        unique (oferta_id, lido_em, fonte)
);

create index if not exists idx_oferta_ads_leituras_oferta_lido_em
on public.oferta_ads_leituras (oferta_id, lido_em desc);

create index if not exists idx_oferta_ads_leituras_recent_success
on public.oferta_ads_leituras (lido_em desc)
where status = 'success';

alter table public.oferta_ads_leituras enable row level security;

drop policy if exists "Authenticated users can read ads history" on public.oferta_ads_leituras;
create policy "Authenticated users can read ads history"
on public.oferta_ads_leituras
for select
to authenticated
using (true);

insert into public.oferta_ads_leituras (
    oferta_id,
    anuncios_ativos,
    lido_em,
    fonte,
    status
)
select
    id,
    anuncios_ativos,
    coalesce(anuncios_ativos_atualizado_em, created_at, now()),
    'backfill',
    'success'
from public.ofertas
where anuncios_ativos is not null
on conflict (oferta_id, lido_em, fonte) do nothing;

with latest_positive as (
    select
        oferta_id,
        max(lido_em) as last_positive_at
    from public.oferta_ads_leituras
    where status = 'success'
      and anuncios_ativos > 0
    group by oferta_id
),
zero_windows as (
    select
        l.oferta_id,
        min(l.lido_em) as zero_since
    from public.oferta_ads_leituras l
    left join latest_positive p on p.oferta_id = l.oferta_id
    where l.status = 'success'
      and l.anuncios_ativos = 0
      and (p.last_positive_at is null or l.lido_em > p.last_positive_at)
    group by l.oferta_id
),
zero_candidates as (
    select
        o.id,
        coalesce(z.zero_since, o.anuncios_ativos_atualizado_em) as zero_since
    from public.ofertas o
    left join zero_windows z on z.oferta_id = o.id
    where coalesce(o.anuncios_ativos, 0) = 0
      and coalesce(z.zero_since, o.anuncios_ativos_atualizado_em) is not null
)
update public.ofertas o
set
    ads_zero_since = coalesce(o.ads_zero_since, z.zero_since),
    ads_monitoring_status = case
        when now() - coalesce(o.ads_zero_since, z.zero_since) >= interval '3 days' then 'inactive'
        when now() - coalesce(o.ads_zero_since, z.zero_since) >= interval '2 days' then 'cooldown'
        else 'active'
    end,
    ads_inactivated_at = case
        when now() - coalesce(o.ads_zero_since, z.zero_since) >= interval '3 days'
            then coalesce(o.ads_inactivated_at, now())
        else null
    end
from zero_candidates z
where o.id = z.id;

update public.ofertas
set
    ads_monitoring_status = 'active',
    ads_zero_since = null,
    ads_last_positive_at = coalesce(anuncios_ativos_atualizado_em, ads_last_positive_at),
    ads_inactivated_at = null,
    ads_next_check_at = null
where coalesce(anuncios_ativos, 0) > 0;

delete from public.oferta_ads_leituras
where lido_em < now() - interval '7 days';
